import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import FrontMenuLayout from "./layout/frontmenu";
// layout.tsxは共通の外枠
// プロジェクトに必ず1つ必要. ヘッダー・フッターを記述
const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// {children: React.ReactNode}はTypeScriptの型定義.
// React.ReactNode型のchildrenというプロパティを持っているオブジェクト
export default function RootLayout({ children }: { children: React.ReactNode }) {
  // 💡 読み込んだレイアウトにページの中身(children)を渡してそのまま返す
  // これがないと、ページ遷移ができない
  // 引数{children}として、returnの中で描画する
  // 新しいレイアウトを利用する
  return <FrontMenuLayout>{children}</FrontMenuLayout>;
}
